In [3]:
import numpy as np

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((5,5)) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [14]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.5649601 , 0.46875796, 0.18406665, 0.14116975, 0.31172047])

In [16]:
np.random.rand(3,3)

array([[0.98592671, 0.5545891 , 0.93030182],
       [0.58744575, 0.85548767, 0.22970452],
       [0.24683341, 0.43081939, 0.82320776]])

In [17]:
np.random.randn(5,5) #random gaussian distribution

array([[ 0.73076027,  0.44736977, -1.22358014, -0.36010057, -0.38548121],
       [-0.66571659, -1.98563169, -0.90937664,  2.33446359,  0.7311868 ],
       [-0.62242268,  1.90467763,  0.73025239, -0.49839602,  0.25430028],
       [-0.35547057,  0.12447094, -1.00701105, -2.78279422,  0.41281376],
       [ 0.05066501,  2.24250522,  1.02766083,  1.10147984, -2.02384218]])

In [18]:
np.random.randint(0,10,3)

array([3, 3, 9])

In [20]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)
ranarr

array([12, 32, 48, 38,  0, 16, 45,  9, 27,  8])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr

array([12, 32, 48, 38,  0, 16, 45,  9, 27,  8])

In [26]:
ranarr.max()

48

In [27]:
ranarr.min()

0

In [28]:
ranarr.argmax()

2

In [29]:
ranarr.argmin()

4

In [33]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [34]:
arr.dtype

dtype('int64')

In [36]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[1:5]

array([1, 2, 3, 4])

In [40]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[0:5]=100

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
arr = np.arange(0,11)

In [45]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [46]:
slice_of_arr[:]=99

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_copy = arr.copy()

In [49]:
arr_copy[:] = 100

In [52]:
arr_copy


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [54]:
#2d arrays

In [55]:
arr_2d = np.array([[5,10,15],[20,30,40],[5,9,10]])

In [60]:
arr_2d[1][2]

40

In [61]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 30]])

In [63]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
bool_arr = arr>5

In [66]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [67]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [68]:
arr[arr<3]

array([1, 2])

In [69]:
arr_2d=np.arange(50).reshape(5,10)

In [71]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [72]:
arr = np.arange(0,11)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [77]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [80]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [81]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [82]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [83]:
np.log(arr)

<ipython-input-83-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])